language: objective-c
branches:
  only:
    - master
    
script:
  - xctool -workspace Coffee Ratio.xcworkspace -scheme Coffee ratio -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO
  - xctool test -workspace Coffee Ratio.xcworkspace -scheme Coffee RatioTests -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO




