language: objective-c
osx_image: xcode8

branches:
  only:
    - master
    
notifications: never

script:
- xcodebuild -project Coffee Ratio.xcodeproj -target Coffee Ratio -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO



